# A very simple example of text prediction
This example may help you understand how large language models are created.

In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import SimpleRNN, Dense, Input
from keras.utils import to_categorical

The neural network will be very simple. We will try to teach it the following text.

We will ask the neural network to complete the rest of the sentence when we enter the beginning of the sentence.

In [2]:
text = "Artificial intelligence is the best and bright future of humanity matrix"

# Data preparation
Split the sentence into letters and create a set of letters used in the sentence.

LLM does not split the text into letters, but into tokens. A token can be a word or part of a word.

In [3]:
chars = sorted(list(set(text)))
print (chars)

[' ', 'A', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'l', 'm', 'n', 'o', 'r', 's', 't', 'u', 'x', 'y']


Neural networks work with numbers and symbols. Therefore, we need to create dictionaries that map numbers to characters and vice versa.

In [4]:
char_to_index = {char: i for i, char in enumerate(chars)}
index_to_char = {i: char for i, char in enumerate(chars)}

In [5]:
char_to_index

{' ': 0,
 'A': 1,
 'a': 2,
 'b': 3,
 'c': 4,
 'd': 5,
 'e': 6,
 'f': 7,
 'g': 8,
 'h': 9,
 'i': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'r': 15,
 's': 16,
 't': 17,
 'u': 18,
 'x': 19,
 'y': 20}

In [6]:
index_to_char

{0: ' ',
 1: 'A',
 2: 'a',
 3: 'b',
 4: 'c',
 5: 'd',
 6: 'e',
 7: 'f',
 8: 'g',
 9: 'h',
 10: 'i',
 11: 'l',
 12: 'm',
 13: 'n',
 14: 'o',
 15: 'r',
 16: 's',
 17: 't',
 18: 'u',
 19: 'x',
 20: 'y'}

We'll make the sentences into sequences. The sentence is chopped into sequences of 3 letters. The sequence will be named with the following letter.

In [7]:
seq_length = 3
sequences = []
labels = []
 
for i in range(len(text) - seq_length):
    seq = text[i:i+seq_length]
    label = text[i+seq_length]
    sequences.append([char_to_index[char] for char in seq])
    labels.append(char_to_index[label])

Convert to numpy array

In [8]:
X = np.array(sequences)
y = np.array(labels)

Sample of the first sequence.

The input letters (numbers) Ume are followed by the letter l.

In [10]:
print ("Art")
print (X[0])

print ("i")
print (y[0])

Art
[ 1 15 17]
i
10


Converting data to categorical - probability of feature occurrence.

In [11]:
X_train = to_categorical(X, len(chars))
Y_train = to_categorical(y, len(chars))

In [12]:
X_train[0]

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0.]])

In [13]:
Y_train[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.])

# Neural network

The neural network will select which category the 3 input letters belong to. 

The category name will be the expected next letter after the 3 input letters.

We will choose the layer SimpleRNN.

In [14]:
model = Sequential()
model.add(Input(shape=(seq_length, len(chars)))) 
model.add(SimpleRNN(50, activation='relu'))
model.add(Dense(len(chars), activation='softmax'))

## Training the model

In [15]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [16]:
model.fit(X_train, Y_train, epochs=100)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.0675 - loss: 3.0760 
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0825 - loss: 3.0410
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0904 - loss: 3.0234
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.0943 - loss: 2.9875
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0904 - loss: 2.9695
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.1088 - loss: 2.9542
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.1166 - loss: 2.9291
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.1238 - loss: 2.9089
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.1277 - loss: 2.8907
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.1154 - loss: 2.8766
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.1467 - loss: 2.8535
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.1394 - l

# Starting the model
Pass the first 6 characters to the model and let it generate 50 characters.
* Select the last 3 characters from the string
* Convert the three characters to categorical input data
* Perform a single character prediction
* The prediction returns the probabilities of the different characters
* Select the character with the highest probability of being true
* Add the character at the end of the text and repeat

In [17]:
start_seq = "Artif"
generated_text = start_seq
 
for i in range(50):
    # create input data from last 3 characters
    x = np.array([[char_to_index[char] for char in generated_text[-seq_length:]]])
    
    # convert to categorical
    x_input = to_categorical(x, len(chars))
    
    # character prediction
    prediction = model.predict(x_input)
    print (prediction)
    
    # selection of the most probable character - class number
    next_index = np.argmax(prediction)

    # convert class number to character
    next_char = index_to_char[next_index]
    
    # adding a character to the end of the string
    generated_text += next_char

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step
[[9.2140608e-02 1.3881968e-04 3.3757999e-03 6.5714330e-03 3.1581963e-03
  5.4206802e-03 4.8289064e-02 3.0058622e-03 6.2773684e-03 1.4673612e-02
  5.3726572e-01 8.2537107e-02 4.0537938e-02 5.2083336e-02 2.7663705e-03
  1.0028163e-02 1.2856803e-02 2.8234275e-02 3.1559590e-02 6.0550687e-03
  1.3024194e-02]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[[9.0535328e-02 1.1105317e-04 7.0110619e-02 1.3349226e-04 5.8687800e-01
  4.3235593e-03 3.0612469e-02 5.5025243e-03 2.4451886e-03 4.7464628e-02
  1.8187630e-04 4.1604806e-03 7.9498120e-04 1.0988850e-02 5.2723195e-04
  2.5328330e-03 1.7933229e-03 1.3401842e-01 5.5911142e-04 6.2719686e-03
  5.3928135e-05]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
[[1.7918516e-02 2.7390048e-05 2.6292840e-03 2.8913768e-03 1.2774356e-03
  7.9251692e-04 1.5234259e-02 6.3378469e-04 1.7191626e-03 1.3182220e-02
  8.2403421e-01 2.1671554e-02 4.0932940e-03 7.0626289e-03 2.0911866e-03
  3.4082841e-02 5.5808463e-04 7.8642266e-03 1.9741828e-02

In [18]:
print (f"Generated text: {generated_text}")

Generated text: Artificial intelligence iftcr iftcr iftcr iftcr iftcr i
